[package]
name = "crystal-vk"
description = "Graphics wrapper for Vulkan"
version = "0.0.1"
edition = "2024"
authors = ["purpflow"]

keywords = ["graphics", "gpu", "gamedev"]
categories = [
    "graphics",
    "computer-vision",
    "game-development",
    "hardware-support",
    "rendering::engine",
]

repository = "https://github.com/purpflow1/crystal-vk"
readme = "README.md"
license = "GPL-3.0-or-later OR MIT"

exclude = ["examples/"]

[profile.release]
opt-level = 3
lto = true
strip = true

[profile.dev]
overflow-checks = true

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
raw-window-handle = "0.6.2"

[dev-dependencies]
shaderc = "0.10.1"
winit = { version = "0.30.10", features = ["rwh_06"] }
glam = "0.30.3"
png = "0.18.0"
futures = "0.3.31"
